rabota:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  slider_controller:
    type: effort_controllers/JointPositionController
    joint: slider_pris_joint
    pid: {p: 300.0, i: 0.00, d: 5}

  link_1_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_Rot_joint
    pid: {p: 500.0, i: 0, d: 0.0}
 
  link_2_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_Rot_joint
    pid: {p: 500.0, i: 0, d: 0.0}

  # trajectory Controllers -> keeping constant velocity of the joints between two points
  rabota_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - slider_pris_joint
      - link_1_Rot_joint
      - link_2_Rot_joint
    gains: # Required because we're controlling an effort interface
      slider_pris_joint:   {p: 300.0, i: 0.0, d: 10.0}
      link_1_Rot_joint:    {p: 300.0, i: 0.0, d: 10.0}
      link_2_Rot_joint:    {p: 300.0, i: 0.0, d: 10.0}
